version: '3'

services:
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${MYSQL_SCHEMA}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3305:3306'
  rabbit:
    image: rabbitmq:3.8.3-management
    container_name: 'rabbitmq-server'
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  redis:
    image: 'redis:alpine'
    container_name: 'redis-server'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - ~/.docker-conf/redis-data:/var/lib/redis
      - ~/.docker-conf/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
